// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }
 
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBywsKq-QJ4cCo7DfZp8TOqkhmjYX4QJH0',
    appId: '1:307265399760:web:965cc146cd85beb23be7d5',
    messagingSenderId: '307265399760',
    projectId: 'fir-87d09',
    authDomain: 'fir-87d09.firebaseapp.com',
    storageBucket: 'fir-87d09.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZwH-ax9MpX5fhDVl74e3ZmtuniwZLxWk',
    appId: '1:307265399760:android:4024d3141dabb6dc3be7d5',
    messagingSenderId: '307265399760',
    projectId: 'fir-87d09',
    storageBucket: 'fir-87d09.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7lnRbgRwSzPK6so9NIUTIW_fNBubgh-Q',
    appId: '1:307265399760:ios:01272970e9d241423be7d5',
    messagingSenderId: '307265399760',
    projectId: 'fir-87d09',
    storageBucket: 'fir-87d09.appspot.com',
    iosBundleId: 'com.example.firebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7lnRbgRwSzPK6so9NIUTIW_fNBubgh-Q',
    appId: '1:307265399760:ios:01272970e9d241423be7d5',
    messagingSenderId: '307265399760',
    projectId: 'fir-87d09',
    storageBucket: 'fir-87d09.appspot.com',
    iosBundleId: 'com.example.firebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBywsKq-QJ4cCo7DfZp8TOqkhmjYX4QJH0',
    appId: '1:307265399760:web:e5a226b81c504fab3be7d5',
    messagingSenderId: '307265399760',
    projectId: 'fir-87d09',
    authDomain: 'fir-87d09.firebaseapp.com',
    storageBucket: 'fir-87d09.appspot.com',
  );
}
